extends:
    - stylelint-config-recommended-scss
rules:
    indentation: 2
    property-no-unknown:
        - true
        - ignoreProperties:
            - appearance
    selector-type-no-unknown:
        - true
        - ignore: custom-elements
    no-descending-specificity:
        - true
        - ignore:
            - selectors-within-list
    color-named: never
    function-url-no-scheme-relative: true
    function-url-scheme-disallowed-list:
        - "/^http/"
    number-max-precision: 6
    shorthand-property-no-redundant-values: true
    value-no-vendor-prefix:
        - true
        - ignoreValues:
            - "/.*fit-content/"
    property-no-vendor-prefix:
        - true
        - ignoreProperties:
            - appearance
            - tab-size
            - touch-action
            - text-size-adjust
    declaration-block-no-redundant-longhand-properties: true
    declaration-no-important:
    declaration-property-unit-allowed-list:
        - font-size:
            - rem
            - em
            - "%"
    declaration-property-value-disallowed-list:
        - border:
            - none
        - border-style:
            - none
    declaration-block-single-line-max-declarations: 1
    selector-max-empty-lines: 0
    selector-max-id: 1
    selector-max-universal: 1
    selector-no-qualifying-type:
        - true
        - ignore:
            - attribute
    selector-no-vendor-prefix:
        - true
        - ignoreSelectors:
            - "::-webkit-input-placeholder"
            - "/-moz-.*/"
    media-feature-name-no-vendor-prefix: true
    at-rule-no-vendor-prefix: true
    at-rule-property-required-list:
        - font-face:
            - font-display
            - font-family
            - font-style
            - src
    color-hex-case: lower
    color-hex-length: short
    font-weight-notation: named-where-possible
    font-family-name-quotes: always-where-recommended
    function-comma-newline-after: never-multi-line
    function-comma-newline-before: never-multi-line
    function-comma-space-after: always
    function-comma-space-before: never
    function-max-empty-lines: 0
    function-name-case: lower
    function-parentheses-newline-inside: never-multi-line
    function-parentheses-space-inside: never-single-line
    function-url-quotes: always
    function-whitespace-after: always
    number-leading-zero: never
    number-no-trailing-zeros: true
    length-zero-no-unit: true
    value-keyword-case:
        - lower
        - ignoreKeywords:
            - BlinkMacSystemFont
            - -apple-system
    value-list-comma-newline-after: never-multi-line
    value-list-comma-newline-before: never-multi-line
    value-list-comma-space-after: always
    value-list-comma-space-before: never
    value-list-max-empty-lines: 0
    property-case: lower
    declaration-bang-space-after: never
    declaration-bang-space-before: always
    declaration-colon-space-after: always
    declaration-colon-space-before: never
    declaration-block-semicolon-newline-after: always
    declaration-block-semicolon-newline-before: never-multi-line
    declaration-block-semicolon-space-after: always-single-line
    declaration-block-semicolon-space-before: never
    declaration-block-trailing-semicolon: always
    block-closing-brace-empty-line-before: never
    block-closing-brace-newline-after:
        - always
        - ignoreAtRules:
            - if
            - else
    block-closing-brace-newline-before: always
    block-closing-brace-space-before: always-single-line
    block-opening-brace-newline-after: always
    block-opening-brace-space-after: always-single-line
    block-opening-brace-space-before: always
    selector-attribute-brackets-space-inside: never
    selector-attribute-operator-space-after: never
    selector-attribute-operator-space-before: never
    selector-attribute-quotes: always
    selector-combinator-space-after: always
    selector-combinator-space-before: always
    selector-descendant-combinator-no-non-space: true
    selector-pseudo-class-case: lower
    selector-pseudo-class-parentheses-space-inside: never
    selector-pseudo-element-case: lower
    selector-pseudo-element-colon-notation: double
    selector-type-case: lower
    selector-list-comma-newline-after: always
    selector-list-comma-newline-before: never-multi-line
    rule-empty-line-before:
        - always
        - ignore:
            - after-comment
            - first-nested
    media-feature-colon-space-after: always
    media-feature-colon-space-before: never
    media-feature-name-case: lower
    media-feature-parentheses-space-inside: never
    media-feature-range-operator-space-after: always
    media-feature-range-operator-space-before: always
    media-query-list-comma-newline-after: never-multi-line
    media-query-list-comma-newline-before: never-multi-line
    media-query-list-comma-space-after: always
    media-query-list-comma-space-before: never
    at-rule-empty-line-before:
        - always
        - except:
            - blockless-after-same-name-blockless
            - blockless-after-blockless
            - first-nested
        - ignoreAtRules:
            - else
            - for
            - forward
            - function
            - if
            - import
            - include
            - keyframes
            - media
            - mixin
            - use
    at-rule-name-case: lower
    at-rule-name-space-after: always
    at-rule-semicolon-newline-after: always
    at-rule-semicolon-space-before: never
    comment-empty-line-before:
        - always
        - except:
            - first-nested
        - ignore:
            - after-comment
            - stylelint-commands
    comment-whitespace-inside: always
    max-empty-lines: 3
